name: gen-models
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.10
  - pip
  - pytorch
  - peft
  - numpy
  - pandas
  - scikit-learn
  - transformers
  - sentence-transformers
  - sentencepiece
  - optuna
  - wandb
  - tqdm
  - torchmetrics
  - pyparsing
