name: amalgam
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - pytorch-cuda=12.1
  - transformers
  - bitsandbytes
  - accelerate
  - peft
  - datasets
  - evaluate
  - pyparsing
  - numpy
  - pandas
  - scikit-learn
  - sentence-transformers
  - sentencepiece
  - protobuf
  - wandb
  - tqdm
  - ipykernel
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - --extra-index-url https://download.pytorch.org/whl/cu121