name: amalgam
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - transformers
  - bitsandbytes
  - accelerate
  - peft
  - datasets
  - evaluate
  - pyparsing
  - numpy
  - pandas
  - scikit-learn
  - sentence-transformers
  - sentencepiece
  - protobuf
  - wandb
  - tqdm
  - ipykernel