compute_environment: LOCAL_MACHINE
distributed_type: FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: true
mixed_precision: fp16
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 8
